apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmchartdemo.fullname" . }}
  labels:
    {{- include "helmchartdemo.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.properties | nindent 4 }}
