apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchartdemo.fullname" . }}
  labels:
    {{- include "helmchartdemo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "helmchartdemo.selectorLabels" . | nindent 4 }}
